apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
  labels:
    app: web-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
      - name: web
        image: sambit1996/docker:spring1
        ports:
        - containerPort: 9090


---

apiVersion: v1
kind: Service
metadata:
  name: my-service3
spec:
  type: NodePort
  selector:
    app: web-app 
  ports:
    - port: 9090
      targetPort: 9090
      # Optional field
      # By default and for convenience, the Kubernetes control plane
      # will allocate a port from a range (default: 30000-32767)
      nodePort: 30003

        
